### ISSUE TITLE
关于怎么切换数据库

### ISSUE THREAD

**Issue by jiulingchen** [hs-web/hsweb-demo#1]
请问此项目怎么切换数据库为mysql或者Oracle呢？

**Comment by zhou-hao** [comment]
@jiulingchen 是动态切换数据源么？还是只是修改默认数据源为mysql或者oracle？
1. 如果是动态切换数据源，使用 `DynamicDataSource.use(dataSourceId)`切换,或者注解@UseDataSource(dataSourceId)
2. 如果是修改默认数据源，修改`application.yml`中的数据源url即可。
