### ISSUE TITLE
The type org.hsweb.web.service.commons.SimpleUpdateService cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by MarsZhu** [hs-web/hsweb-demo#3]
How to solve this problem "The type org.hsweb.web.service.commons.SimpleUpdateService cannot be resolved. It is indirectly referenced from required .class files"

**Comment by zhou-hao** [comment]
could you show me your code,and the environment you use?

**Comment by MarsZhu** [comment]
![Uploading QQ截图20170511210713.png…]()
Like this！

**Comment by MarsZhu** [comment]
I update myeclispe to 2017 in order to use jdk1.8. The problem is solved. Thank you!
