### ISSUE TITLE
运行没有问题，但是我想看实现这些功能的源码，在这个hsweb-demo中并没有，全是用Maven实现的依赖

### ISSUE THREAD

**Issue by CraftLCL** [hs-web/hsweb-demo#7]
运行没有问题，但是我想看实现这些功能的源码，在这个hsweb-demo中并没有，全是用Maven实现的依赖，实现这个demo的所有代码在哪看呀？

**Comment by zhou-hao** [comment]
框架代码  https://github.com/hs-web/hsweb-framework

**Comment by CraftLCL** [comment]
这个代码我也在读，我感觉如果实现例子的代码能有的话，可以让hsweb-framework的理解使用更加方便。

**Comment by kksh3ll** [comment]
idea导了一个晚上，还在不停的解析依赖，看着都怕

**Comment by zhou-hao** [comment]
@kksh3ll 估计你打开方式有问题。我这挺快滴啊
